name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows manual workflow runs from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "continuous_integration"
  continuous_integration:
    # The type of runner the job will run on
    runs-on: ubuntu-latest

    # Steps executed as part of the job
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Runs a single command
      - name: Run a one-line script
        run: echo Start to test and build the artifact

      # Runs go test and go build
      - name: Run test and build
        run: |
          go test -v ./.
          CGO_ENABLED=0 GOARCH=amd64 go build -o demo

      # Declare variables (short Git commit SHA)
      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      # Boot Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ steps.vars.outputs.sha_short }}
